version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/project

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  lint-and-flow:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/project
        - run: |
            yarn run lint
            yarn run flow

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint-and-flow:
          requires:
            - install-dependencies
